=begin
	
	v1.0.0  by sxysxy           2016.03.30
=end

require 'XYGui/winapi_base.rb'
require 'XYGui/xy_widget.rb'

class XYTrackBar < XYWidget

=begin
	TBS_AUTOTICKS = 1
	TBS_VERT = 2
	TBS_HORZ = 0
	TBS_TOP	= 4
	TBS_BOTTOM = 0
	TBS_LEFT = 4
	TBS_RIGHT = 0
	TBS_BOTH = 8
	TBS_NOTICKS	= 16
	TBS_ENABLESELRANGE = 32
	TBS_FIXEDLENGTH	= 64
	TBS_NOTHUMB	= 128

	TBS_TOOLTIPS = 0x0100
	TBTS_TOP = 0
	TBTS_LEFT = 1
	TBTS_BOTTOM = 2
	TBTS_RIGHT = 3

	TBS_REVERSED = 0x0200

	
	TBS_DOWNISLEFT = 0x0400

	TBIF_BYINDEX = 0x80000000
	TBIF_COMMAND = 32
	TBIF_IMAGE = 1
	TBIF_LPARAM = 16
	TBIF_SIZE = 64
	TBIF_STATE = 4	
	TBIF_STYLE = 8
	TBIF_TEXT = 2

	TBM_GETPOS = WM_USER
	TBM_GETRANGEMIN	= WM_USER+1
	TBM_GETRANGEMAX	= WM_USER+2
	TBM_GETTIC = WM_USER+3
	TBM_SETTIC = WM_USER+4
	TBM_SETPOS = WM_USER+5
	TBM_SETRANGE = WM_USER+6
	TBM_SETRANGEMIN	= WM_USER+7
	TBM_SETRANGEMAX	= WM_USER+8
	TBM_CLEARTICS = WM_USER+9
	TBM_SETSEL = WM_USER+10
	TBM_SETSELSTART	= WM_USER+11
	TBM_SETSELEND = WM_USER+12
	TBM_GETPTICS = WM_USER+14
	TBM_GETTICPOS = WM_USER+15
	TBM_GETNUMTICS = WM_USER+16
	TBM_GETSELSTART = WM_USER+17
	TBM_GETSELEND = WM_USER+18
	TBM_CLEARSEL = WM_USER+19
	TBM_SETTICFREQ = WM_USER+20
	TBM_SETPAGESIZE = WM_USER+21
	TBM_GETPAGESIZE = WM_USER+22
	TBM_SETLINESIZE = WM_USER+23
	TBM_GETLINESIZE	= WM_USER+24
	TBM_GETTHUMBRECT = WM_USER+25
	TBM_GETCHANNELRECT = WM_USER+26
	TBM_SETTHUMBLENGTH = WM_USER+27
	TBM_GETTHUMBLENGTH = WM_USER+28
	TBM_SETTOOLTIPS	= WM_USER+29
	TBM_GETTOOLTIPS	= WM_USER+30
	TBM_SETTIPSIDE = WM_USER+31
	TBM_SETBUDDY = WM_USER+32
	TBM_GETBUDDY = WM_USER+33
	TB_LINEUP = 0
	TB_LINEDOWN	= 1
	TB_PAGEUP = 2
	TB_PAGEDOWN	= 3
	TB_THUMBPOSITION = 4
	TB_THUMBTRACK = 5
	TB_TOP = 6
	TB_BOTTOM = 7
	TB_ENDTRACK	= 8
=end

	def initialize(app, parent, arg = {})
		super(app, parent, arg)
		create if self.class == XYTrackBar
	end
	
	def create
		@handle = WinAPI.call("user32", "CreateWindowEx", 0, "msctls_trackbar32", "", 
								WS_CHILD,
								@x, @y, @width, @height, 
								@parent.handle,@id, 
								@app.instance,
								0)
	end
	
	def defaultWidth
		200
	end
	
	def defaultHeight
		30
	end
	
end